spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      format-sql: true
  h2:
    console:
      enabled: true

encrypt:
  aes:
    key: os+18F4z1/SsgX9hWZdS41CKPqdhT---
    iv: 1234567890123---
